#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"

jq -n \
--arg request_type "InstallMedia" \
--arg udid "$1" \
--arg media_url "$2" \
'
.udid = $udid
|.request_type = $request_type
|.media_url = $media_url
|.media_type = "Book"
|.author = "Achim"
|.kind = "pdf"
|.persistent_id = "com.acme.pdf.myenterprisebook"
|.title = "My Enterprise Book"
|.version = "1.0"
'|\
curl -v $CURL_OPTS \
-H "Content-Type: application/json" \
-u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-
